### PR TITLE
Safe.md

### PR DESCRIPTION
**Pull request by s1-12**
Sorry supertux people

### CODE REVIEW

**Comment by Vankata453** [comment]
This looks like an empty template, what is the point of this pull request?

**Comment by s1-12** [comment]
Tell the supertux people to unban me in github

**Comment by s1-12** [comment]
And the point of this is to make security md

**Comment by Vankata453** [comment]
Since this pull request is just an empty template and there isn't an apparent purpose for it, I will close this. Please do not make issues or pull requests that do not serve any purpose, that may have been the reason you were banned in the first place.

**Pull request closed without merging**
